### ISSUE TITLE
Optifine is not compatible...

### ISSUE THREAD

**Issue by DoricSan** [benbenlaw/caveopolis#27] opened 2022-10-04 11:52 UTC
Hey there,

Thank you for your nice work !
Unfortunately OptiFine_1.18.2_HD_U_H7 is not compatible and it's impossible to launch a game with it.
Is any solution possible?

Thanks !

**Comment by CharZinta** [comment] 2022-10-04 22:20
The below is information found in the discord channel. The following statement does not mean Ben will not help but rather what I found when looking into Optifine to support an answer to your question.

LotP — 07/24/2021
Optifine changes parts of Minecrafts rendering engine to make it more performant
most of the time they do this by directly replacing/overwriting code or changing formulas used in computing
the problem is that forge and many mods rely on the original code and functions, so the mods break when they try to use optifine functions
and Optifine doesn't want to make it forge compatible because then they would basically have to revert all their changes
that's why Optifine is fine for vanilla, but sucks for modded 99% of the time
this is also why we don't recommend using fps boosters etc. because they work in the same way as Optifine, they replace code which can break mods

**Comment by humanitea** [comment] 2023-02-17 16:43
As CharZinta said, Optifine is not well supported for Forge Modpacks. The Compatibility is not an issue with this pack so much as it is the way Optifine handles things on its end.

Closing this issue.

**Closed as completed by humanitea** 2023-02-17 16:43 UTC
Labels: not a bug
